INSERT INTO razas (raza, tamano) VALUES
('Mestizo', 'variable'),
('Chihuahua', 'pequeno'),
('Xoloitzcuintle', 'variable'),
('Pastor Alemán', 'grande'),
('Labrador Retriever', 'grande'),
('Golden Retriever', 'grande'),
('Pug', 'pequeno'),
('Bulldog Inglés', 'mediano'),
('Bulldog Francés', 'pequeno'),
('Beagle', 'mediano'),
('Boxer', 'grande'),
('Rottweiler', 'grande'),
('Doberman', 'grande'),
('Schnauzer Miniatura', 'pequeno'),
('Schnauzer Mediano', 'mediano'),
('Schnauzer Gigante', 'grande'),
('Poodle Toy', 'pequeno'),
('Poodle Miniatura', 'pequeno'),
('Poodle Estándar', 'mediano'),
('Yorkshire Terrier', 'pequeno'),
('Shih Tzu', 'pequeno'),
('Maltés', 'pequeno'),
('Cocker Spaniel', 'mediano'),
('Border Collie', 'mediano'),
('Husky Siberiano', 'mediano'),
('Pitbull Terrier', 'mediano'),
('American Staffordshire Terrier', 'mediano'),
('Bull Terrier', 'mediano'),
('Dachshund', 'pequeno'),
('Basset Hound', 'mediano'),
('Dálmata', 'grande'),
('Gran Danés', 'gigante'),
('San Bernardo', 'gigante'),
('Akita Inu', 'grande'),
('Shiba Inu', 'pequeno'),
('Chow Chow', 'mediano'),
('Shar Pei', 'mediano'),
('Pastor Belga Malinois', 'grande'),
('Pastor Australiano', 'mediano'),
('Corgi Galés Pembroke', 'pequeno'),
('Boston Terrier', 'pequeno'),
('Jack Russell Terrier', 'pequeno'),
('Weimaraner', 'grande'),
('Pointer Inglés', 'grande'),
('Setter Irlandés', 'grande'),
('Cane Corso', 'grande'),
('Mastín Napolitano', 'gigante'),
('Bichón Frisé', 'pequeno'),
('Papillón', 'pequeno'),
('Pomerania', 'pequeno');